# Generated by Django 3.0.7 on 2020-07-01 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_title', models.CharField(max_length=64)),
                ('body', models.TextField()),
                ('answers_count', models.IntegerField()),
            ],
        ),
    ]
