# Generated by Django 3.1b1 on 2020-07-03 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("subjects", "0001_initial"),
        ("questions", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="question", old_name="subject_title", new_name="title",
        ),
        migrations.RemoveField(model_name="question", name="answers_count",),
        migrations.AddField(
            model_name="question",
            name="subject",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="subjects.subject",
            ),
            preserve_default=False,
        ),
    ]
